services:
  - type: web
    name: tds-fastapi
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app:app --host=0.0.0.0 --port=10000"
    autoDeploy: true
    plan: free
    region: oregon
    branch: main
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"